### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by qskwood** [anode-co/AnodeVPN-android#26]
What are the device requirements for this app?

(When I try on my Galaxy A11 I get "App not installed." with no further explanation. When I try on Bluestacks I get another vauge error with no diagnostic information.)

**Comment by qskwood** [comment]
I have "downgraded" the SDK requirement to 25 in an attempt to get it running under BlueStacks.

I get the following error output, which may simply be because SDK 26 or higher is required:
```
$ am start --user 0 -n co.anode.anodium/co.anode.anodium.VpnListActivity
Starting: Intent { cmp=co.anode.anodium/.VpnListActivity }
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=co.anode.anodium/.VpnListActivity } from null (pid=15445, uid=2000) not exported from uid 10060
        at android.os.Parcel.readException(Parcel.java:1692)
        at android.os.Parcel.readException(Parcel.java:1645)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:3152)
        at com.android.commands.am.Am.runStart(Am.java:643)
        at com.android.commands.am.Am.onRun(Am.java:394)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:124)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:352)
```

**Comment by dkoukoul** [comment]
I do not have experience with BlueStacks but from the error it seems that it is a permission denial so not something to do with the SDK. If you want to run it under an emulator I would suggest the Android Studio emulator which I can guarantee that it is running on.

**Comment by dkoukoul** [comment]
I'll close this as we will not try to make it work on BlueStacks but it should install now on Galaxy A11 since the build now has armv7a
