### ISSUE TITLE
Stuck on white screen

### ISSUE THREAD

**Issue by kaotisk-hund** [anode-co/AnodeVPN-android#3]
Application does not open on my Xiaomi Redmi 6A.
* Tested versions: 0.1.23, 0.1.24
* Android version: 9 PPR1.180610.011
* Command for running: `$ am start --user 0 -n co.anode.anodium/co.anode.anodium.VpnListActivity`

```
Starting: Intent { cmp=co.anode.anodium/.VpnListActivity }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.example.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.example.termuxam.IActivityManager.startActivityAsUser(IActivityManager.java:165)
        at com.example.termuxam.Am.runStart(Am.java:635)
        at com.example.termuxam.Am.onRun(Am.java:353)
        at com.example.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.example.termuxam.Am.main(Am.java:74)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=co.anode.anodium/.VpnListActivity } from null (pid=14916, uid=10155) not exported from uid 10175
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IActivityManager$Stub$Proxy.startActivityAsUser(IActivityManager.java:6728)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1868)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:763)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:556)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1231)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:495)
```

**Comment by dkoukoul** [comment]
this issue has been fixed
